import type {Job,InterviewReview,CalendarEvent,InboxItem,Material,ProjectExperience} from './types';
// Everything in this file is fictional. Public company names do not imply real applications.
const day=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const review:InterviewReview={id:'demo-review-product',date:day(-2),round:'一面 · 虚构演练',result:'待通知',source:'为展示复盘功能编写的模拟面试，不是真实企业面经',summary:'这次模拟围绕校园活动报名工具展开：能说明资料分散与重复登记的问题，但从需求排序到上线验证的回答还不够具体。下一次用一个关键路径和两项验证指标回答。',positiveSignals:['能区分组织者和参与者的不同目标','用实际操作路径解释功能取舍'],improvementAreas:['先回答结论，再补背景，避免介绍工具占用太多时间','区分模型生成结果与人工核验，不把能生成等同于正确'],questions:[{question:'为什么不直接用一张共享表格？',intent:'考察是否理解替代方案以及产品增量价值',reflection:'回答了表格不直观，但没有说明持续使用时的成本。',linkedExperience:'校园活动报名助手（虚构课程项目）',answerStrategy:'先承认表格适合低频协作，再解释信息确认、截止提醒和个人进度之间的衔接。',betterAnswer:'如果只有一次活动，一张表就够了。我们的场景是每周不同活动、多渠道收集报名和临时改期。原型把原始通知、报名状态和变更提醒连接起来，优先解决重复确认，而不重新实现所有表格功能。'},{question:'你怎么判断 AI 生成的活动摘要可用？',intent:'考察结果评估与错误处理',reflection:'只说了人工检查，缺少样例与规则。',linkedExperience:'通知字段整理原型',answerStrategy:'定义需要正确的字段，保留原文，覆盖歧义与缺失值。',betterAnswer:'我会先检查时间、地点、对象和报名入口。对时间缺失、通知改期、多个链接等样例逐项比较；摘要旁保留来源。未确认的信息不进入提醒，用户确认后才保存。这是下一轮计划验证的方法，不是已经得到的效果数据。'}],nextSteps:['补充一分钟项目说明：用户—痛点—取舍—结果','准备三类解析失败样例','按真实证据整理可展示截图，不夸大测试规模']};
const stages:Job['status'][]=['materials','interview','applied','test','wish','shelved'];
const actions=['按产品岗位要求压缩项目描述，准备一页作品说明','根据模拟复盘练习需求取舍与结果验证的回答','核对申请材料版本，等待下一步通知（虚构进度）','安排一次限时练习，检查网络与设备','查看岗位职责与工作城市，决定是否加入本周计划','暂缓推进，保留公司资料供后续比较'];
export function demoJobs(jobs:Job[]):Job[]{return jobs.map((job,i)=>i<6?{...job,status:stages[i],isFavorite:true,isInApplicationTracker:i<4,nextAction:`【虚构演示】${actions[i]}`,nextActionDate:day(i%3),connectedMaterials:['demo-resume','demo-intro'],connectedProjects:['demo-campus-tool'],connectedNotes:['knowledge-cx-ai-framework'],interviewReviews:i===1?[review]:[]}:job);}
export const DEMO_CALENDAR:CalendarEvent[]=[
{id:'demo-event-prep',title:'完善产品方向简历（虚构安排）',type:'custom',date:day(),time:'19:00',companyName:'个人准备',completed:false,notes:'对照目标岗位，统一项目贡献、时间和链接；导出之前检查联系方式。'},
{id:'demo-event-test',title:'限时笔试练习（虚构安排）',type:'test',date:day(1),time:'10:00',jobId:'real-j-4',companyName:'练习日程',completed:false,notes:'留出90分钟，结束后记录易错题。非企业真实笔试通知。'},
{id:'demo-event-interview',title:'产品模拟面试（虚构安排）',type:'interview',date:day(2),time:'15:00',jobId:'real-j-2',companyName:'同伴模拟',completed:false,notes:'准备三分钟项目介绍、需求排序与AI结果评估；结束后写入面试复盘。'},
{id:'demo-event-summary',title:'本周申请与资料复盘（虚构安排）',type:'custom',date:day(4),time:'20:00',companyName:'个人准备',completed:false,notes:'清理重复线索，检查待确认日期，更新下一步行动。'}];
export const DEMO_INBOX:InboxItem[]=[
{id:'demo-inbox-1',title:'校园产品助理机会 · 待核对',content:'【虚构线索】星舟校园服务团队计划招募产品助理。方向：活动发现、报名流程和用户反馈；城市：杭州。需到正式公告核对申请条件和截止时间，当前未提供可信报名入口。',source:'校园交流频道（虚构）',sourceType:'wechat',detectedCompany:'星舟校园服务（虚构）',detectedJob:'产品助理',detectedCity:'杭州',detectedDeadline:'',detectedApplyUrl:'',status:'pending',collectedAt:day(),needsConfirmation:true},
{id:'demo-inbox-2',title:'研究生夏令营材料清单 · 场景示例',content:'【虚构场景】远山大学信息管理夏令营：需要成绩单、个人陈述、项目介绍及推荐信。时间与资格尚待官方通知确认。此条用于展示长期申请任务的信息收集，不代表已有真实招生项目。',source:'手动整理（虚构）',sourceType:'manual',detectedCompany:'远山大学（虚构）',detectedJob:'夏令营申请',detectedCity:'',detectedDeadline:'',detectedApplyUrl:'',status:'pending',collectedAt:day(),needsConfirmation:true}];
export const DEMO_MATERIALS:Material[]=[
{id:'demo-resume',title:'林知夏｜产品方向简历（虚构）',type:'resume',version:'v2.1',content:'本页全部为虚构样例。\n林知夏｜2027届信息管理硕士｜lin.zhixia@example.com\n求职方向：产品助理、AI应用产品。\n教育：远山大学信息管理硕士；青禾大学信息系统本科（院校均为虚构）。\n项目：校园活动报名助手。负责访谈提纲、报名路径梳理、原型设计与字段核验；通过AI辅助生成前端，人工检查边界状态。\n实习：星舟校园服务（虚构）产品实习。整理用户反馈、维护需求列表与发布记录。\n工具：Figma、Excel、SQL基础、AI辅助编程。成果以需求文档、交互原型和测试记录为证，不预填提效百分比。',lastUpdated:day(-1),connectedJobs:['real-j-1','real-j-2'],jobDirection:'产品研发'},
{id:'demo-intro',title:'一分钟自我介绍（虚构）',type:'intro',version:'v1.2',content:'面试官您好，我是林知夏，正在学习信息管理。我关注如何把分散信息变成可执行的流程。在虚构课程案例“校园活动报名助手”中，我先梳理组织者发布通知、同学报名及临时改期的路径，再设计通知字段确认和报名状态页面，借助AI辅助实现原型。我希望继续在产品岗位中学习需求判断、体验设计与验证方法。以上为演示人物内容。',lastUpdated:day(-2),connectedJobs:['real-j-2'],jobDirection:'产品研发'},
{id:'demo-checklist',title:'不同网申字段的取用清单（示例）',type:'checklist',version:'v1.0',content:'300字项目简介：背景一句、个人动作两句、交付一句。\n1000字项目经历：补目标用户、功能取舍、迭代过程与验证范围。\n实习职责：写个人参与部分，避免把团队结果全部归为个人。\n提交前：检查起止日期、毕业时间、链接权限、附件版本；未知字段留待确认。\n所有网申仍由使用者人工核对和提交。',lastUpdated:day(),connectedJobs:[]}];
export const DEMO_PROJECTS:ProjectExperience[]=[{id:'demo-campus-tool',title:'校园活动报名助手（虚构课程案例）',role:'需求与交互设计',period:'2026.03—2026.05（虚构）',type:'课程项目',background:'不同社团的活动信息分散在群消息和表格，同学需要反复确认活动时间与报名结果。',task:'围绕活动发现、报名确认与改期提醒，设计一条可验证的用户路径。',action:'梳理组织者与参与者任务；将原始通知、结构化字段和个人报名状态分开；借助AI制作可交互原型，并检查缺失日期和重复报名等情况。',result:'示例交付为需求说明、交互原型及检查清单，不代表真实上线或用户增长。',tools:['Figma','React','AI辅助编程'],starStory:'发现通知分散的问题后，先明确参与者最常需要确认的信息，再把报名与改期场景画成流程。优先完成字段确认和状态查看，暂缓复杂推荐。用样例逐项检查字段与边界情况，记录还需要验证的环节。',resumeSnippet:'围绕校园活动发现与报名场景完成需求梳理、流程设计及AI辅助原型实现，保留来源与字段确认步骤（虚构样例）。',connectedJobs:['real-j-1','real-j-2']}];
